### ISSUE TITLE
Newer version support

### ISSUE THREAD

**Issue by kizzie** [sky-uk/go-brocade-vtm#32]
Kinda the opposite of the other question - I was trying to find something that would support API 5.x (we're running brocade 17.3) and I was so close, then re-read this repo. 

Are you guys thinking of upgrading to support 5.x or should I bite the bullet and start writing it myself?

**Comment by ruimoreira** [comment]
Thanks for raising the issue regarding support for other API versions. We currently have an internal requirement to support other API versions. We haven’t started working on adding this feature. Our first thought was to change the API version to a variable and set values to omit empty in the structs. Not sure if this will work. However please do feel free to submit a pull request with this feature. We’d appreciated it.

**Comment by kizzie** [comment]
Ahh, shall have a ponder and see! We have a similar thing but are trying to go from the older API to the newer one soon. Shall have to continue hunting or actually just knuckle down and build it :)

**Comment by iahmad-khan** [comment]
From my experience so for , its just about having the api as a config variable and everything will work the same as this is working using curl. I dont think they are making any major changes at the backend.
